server:
  port: 8083

spring:
  application:
    name: inventory-service

  flyway:
    schemas: inventory
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        default_schema: inventory

    open-in-view: false

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver

  kafka:
    producer:
      acks: all
      retries: 5
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: inventory-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"
        max.poll.records: 500
        session.timeout.ms: 30000
        heartbeat.interval.ms: 10000

    listener:
      ack-mode: manual_immediate
      concurrency: 3

  jackson:
    time-zone: UTC

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.springframework.security: INFO
    org.springframework.kafka: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

kafka:
  topics:
    inventory-created: inventory.created

